title: Fender Docs

author: okok7711
theme: just-the-docs
style: dark
listen_for_clients_preferred_style: true

mermaid:
  version: "9.1.3"
permalink: pretty

enable_copy_code_button: true

heading_anchors: true

nav_sort: case_sensitive

back_to_top: true
back_to_top_text: "Back to top"

color_scheme: dark

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template